# Important: We should avoid exposing any ports between `20000` and `36384`
# see here for reasons why: https://github.com/logrhythm/boreas/tree/master/documentation/troubleshooting
# boo
version: '3.7'

volumes:
  grafana_data: {}
  pgadmin_data: {}
  postgresql_data: {}
  prometheus_data: {}
  kafka_data: {}
  kafka_zk_conf: {}
  kafka_zk_data: {}

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  haproxy:
    image: mminks/haproxy-docker-logging:latest
    ports:
      - 8000:8000
    volumes:
      - ../haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ../haproxy/certs:/usr/local/etc/haproxy/certs
    networks:
      default:
        ipv4_address: 172.28.1.5

  postgres:
    image: "postgres:latest"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - ../postgresql/01-databases.sql:/docker-entrypoint-initdb.d/01-databases.sql
    ports:
      - "50432:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      default:
        ipv4_address: 172.28.1.25

  pg-admin:
    image: "dpage/pgadmin4:latest"
    volumes:
      - ../pgadmin/servers.json:/pgadmin4/servers.json
      - ../pgadmin/pgpass:/pgadmin4/pgpass
      - pgadmin_data:/var/lib/pgadmin
    expose:
      - 80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: 172.28.1.26

  jaeger:
    image: "jaegertracing/all-in-one:latest"
    ports:
      - "60831:6831/udp"
      - "60832:6832/udp"
      - "50778:5778"
      - "16686:16686"
      - "14268:14268"
      - "19411:9411"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 19411
    networks:
      default:
        ipv4_address: 172.28.1.27

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    expose:
      - 9090
    networks:
      default:
        ipv4_address: 172.28.1.28

  grafana:
    image: grafana/grafana
    volumes:
      - ../grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    env_file:
      - ../grafana/config.monitoring
    expose:
      - 3000
    depends_on:
      - prometheus
    networks:
      default:
        ipv4_address: 172.28.1.29

  infinispan:
    user: root
    image: infinispan/server:10.1.3.Final
    volumes:
      - ../infinispan/entrypoint.sh:/opt/infinispan/server/boreas-entrypoint.sh
      - ../infinispan/infinispan.xml:/opt/infinispan/server/boreas-infinispan.xml
      - ../infinispan/log4j2.xml:/opt/infinispan/server/conf/log4j2.xml
    entrypoint:
      - /opt/infinispan/server/boreas-entrypoint.sh
    ports:
      - 41222:11222
    networks:
      default:
        ipv4_address: 172.28.1.30

  unleash:
    image: unleashorg/unleash-server:3.1
    ports:
      - 4242:4242
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/unleash
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: 172.28.1.31

  keycloak:
    image: jboss/keycloak:9.0.3
    expose:
      - 8080
    volumes:
      - ../keycloak/boreas-realm.json:/tmp/boreas-realm.json
      - ../keycloak/turn-off-theme-caching.sh:/opt/jboss/startup-scripts/turn-off-theme-caching.sh
      - ../../../front-end/.dockerResources/keycloak/themes/logrhythm:/opt/jboss/keycloak/themes/logrhythm
    depends_on:
      - postgres
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
      KEYCLOAK_IMPORT: /tmp/boreas-realm.json
#      KEYCLOAK_DEFAULT_THEME: logrhythm # uncomment when ready
      PROXY_ADDRESS_FORWARDING: "true"
    networks:
      default:
        ipv4_address: 172.28.1.32

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    volumes:
      - kafka_zk_conf:/opt/zookeeper-3.4.6/conf
      - kafka_zk_data:/opt/zookeeper-3.4.6/data
    ports:
      - "2181:2181"
    networks:
      default:
        ipv4_address: 172.28.1.33

  kafka:
    image: wurstmeister/kafka:2.12-2.4.1
    volumes:
      - kafka_data:/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      default:
        ipv4_address: 172.28.1.34
