name: Local Dev Check

on:
  pull_request:
    paths:
      - 'local_dev/**'

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: check-content
        run: |
          # download yq
          curl https://github.com/mikefarah/yq/releases/download/3.3.0/yq_linux_amd64 -o yq --silent
          chmod +x ./yq
          ./scripts/invalid-docker-ports.sh
