name: Local Dev Check

on:
  pull_request:
    paths:
      - 'local_dev/**'

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: check-content
        run: |
          ./scripts/invalid-docker-ports.sh
